### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by dpchris** [TGenNorth/NASP#10]
Hello, 

I tried to run nasp but after i gave all asked informations nasp just print "total_mem = 62"
It seems something is not working at the beginning of the pipeline and it ends in several seconds creating only empty files.

Everything seems to be well installed and functional and i checked input data.
I can't find what the problem is.

I put my command lines here : 

$ nasp
Welcome to NASP version 1.0.0.

Where would you like output files to be written [nasp_results]? results/

Output folder /media/sf_D_DRIVE/David/results already exists!
Files in it may be overwritten!
Should we continue anyway [N]? y

Where is the reference fasta file you would like to use? reference_brucella/Brucella_16M_concatenate.fasta

Do you want to check the reference for duplicated regions
and skip SNPs that fall in those regions [Y]? 

What system do you use for job management (PBS/TORQUE, SLURM, SGE/OGE, and 'none' are currently supported) [PBS]? none

Do you have fasta files for external genomes you wish to include [Y]? n

Do you have read files you wish to include [Y]? y
Where are these files located [/media/sf_D_DRIVE/David]? melitensis_46/

Would you like to use Trimmomatic to trim your reads first [N]? 

This pipeline currently supports four aligners: BWA, Bowtie2, Novoalign, and SNAP.
You can also provide pre-aligned BAM files, and you can choose as many options as you want.

Would you like to run BWA mem [Y]? 
Would you like to set advanced BWA-mem settings [N]? 

Would you like to run Bowtie2 [Y]? n

Would you like to run Novoalign [N]? 

Would you like to run SNAP [N]? 

Do you have pre-aligned SAM/BAM files you wish to include [N]? 

This pipeline currently supports four SNP callers: GATK, SolSNP, VarScan, and SAMtools, and you can provide VCF files.
You can choose as many options as you want.

Would you like to run GATK [Y]? 
Would you like to set advanced GATK settings [N]? 

Would you like to run SolSNP [N]? 

Would you like to run VarScan [Y]? n

Would you like to run SAMtools [Y]? 
Would you like to set advanced SAMtools settings [N]? 

Do you have pre-called VCFfiles you wish to include [N]? 

This pipeline can do filtering based on coverage.
If you do not want filtering based on coverage, enter 0.
What is your minimum coverage threshold [10]? 

This pipeline can do filtering based on the proportion of reads that match the call made by the SNP caller.
If you do not want filtering based on proportion, enter 0.
What is the minimum acceptable proportion [0.9]? 
Would you like to set advanced MatrixGenerator settings [N]? 

Do you want to create a master_masked matrix that includes all positions with low-quality positions that failed the coverage or proportion filter masked with an 'N' [N]? 
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62

Maybe the problem comes from the fact I don't use a system for job management.

Can someone help me ?

Thanks in advance.

**Comment by corburn** [comment]
Hello @dpchris,

Which operating system are you using and can you check to see if any of the programs (samtools/GATK/etc) are still running?

**Comment by dpchris** [comment]
Hello,

I'm using ubuntu 16.04 LTS.

I don't know how to check if it is still running, nasp just closed in few seconds.
You mean job are actually running after that and nasp just start it ?

Sorry I don't know how to check it, I have no job management since i tried on my pc.

Can you tell me how to see if jobs are running ?

regards.



________________________________
De : Jason Travis [notifications@github.com]
Envoyé : mardi 31 janvier 2017 15:54
À : TGenNorth/NASP
Cc : CHRISTIANY David; Mention
Objet : Re: [TGenNorth/NASP] run failed (#10)


Hello @dpchris<https://github.com/dpchris>,

Which operating system are you using and can you check to see if any of the programs (samtools/GATK/etc) are still running?

**Comment by corburn** [comment]
On Ubuntu the Gnome System Monitor can be used to view running programs. https://www.youtube.com/watch?v=ufWL6FxplV4

**Comment by dpchris** [comment]
After I ran nasp, I have several new processus named sh and sleep.
So it seems to work, but none of these processus seems to be active.
Is it normal ?
________________________________
De : Jason Travis [notifications@github.com]
Envoyé : mardi 31 janvier 2017 16:12
À : TGenNorth/NASP
Cc : CHRISTIANY David; Mention
Objet : Re: [TGenNorth/NASP] run failed (#10)


On Ubuntu the Gnome System Monitor can be used to view running programs. https://www.youtube.com/watch?v=ufWL6FxplV4

**Comment by corburn** [comment]
Hello @dpchris,

The error log was helpful, thank you. To patch this error you need Samtools prior to version 1.

NASP needs to be updated to support both Samtools pre and post version 1.0.
During development a couple options were tested, but did not make it into the release.

**Comment by dpchris** [comment]
Ok, I see.
So what is the best version of samtools for nasp ?
________________________________
De : Jason Travis [notifications@github.com]
Envoyé : mardi 31 janvier 2017 20:03
À : TGenNorth/NASP
Cc : CHRISTIANY David; Mention
Objet : Re: [TGenNorth/NASP] run failed (#10)


Hello @dpchris<https://github.com/dpchris>,

The error log was helpful, thank you. To patch this error you need Samtools prior to version 1.

NASP needs to be updated to support both Samtools pre and post version 1.0.
During development a couple options were tested, but did not make it into the release.

**Comment by corburn** [comment]
Hello @dpchris,

I will review this later today, but skimming the changelog it appears the breaking changes were made in [samtools 1.3](https://github.com/samtools/samtools/releases/tag/1.3). Samtools prior to 1.3 should be compatible. Samtools prior to 1.0 will be compatible.

**Comment by yseif** [comment]
I'm getting the same error today. 

bin/sh: 1: [: -lt: unexpected operator
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[M::process] read 264932 sequences (40000195 bp)...
[M::process] read 264940 sequences (40000046 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (48, 124175, 19, 45)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (251, 2030, 6720)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19658)
[M::mem_pestat] mean and std.dev: (3674.85, 3528.39)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 26127)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (337, 434, 523)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 895)
[M::mem_pestat] mean and std.dev: (427.68, 112.44)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1081)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (629, 1561, 3677)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 9773)
[M::mem_pestat] mean and std.dev: (2039.11, 1699.18)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 12821)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (263, 659, 6786)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19832)
[M::mem_pestat] mean and std.dev: (3588.33, 3453.89)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 26355)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 264932 reads in 16.240 CPU sec, 4.384 real sec
[E::hts_open_format] Failed to open file SRR7748055-ni	
samtools index: failed to open "SRR7748055-bwamem.bam": No such file or directory


My NASP version is:
This is the "Northern Arizona SNP Pipeline", version 1.1.2

My Samtools version is:
samtools 1.9
Using htslib 1.9

**Comment by corburn** [comment]
Hello @yseif, the NASP dispatcher still uses the flags for samtools before 1.3.

**Comment by yseif** [comment]
I see, so I downloaded samtools 1.2. and updated the path directory. NASP successfully recognizes samtools 1.2 now but the job is not getting done. Instead, trimmomatic runs just fine (with all the ouput files saved in the "trimmed' folder as expected, but the bwamem.out file is empty and there are no other files in the 'bwamem' folder. When I go into the command line and run the command obtained from the runlog.txt file:

/usr/bin/bwa mem -R '@RG\tID:SRR7748055\tSM:SRR7748055'  -t 4 /chosen_path/reference/reference.fasta /chosen_path/trimmed/SRR7748055_R1_trimmed.fastq /chosen_path/trimmed/SRR7748055_R2_trimmed.fastq | /home/yara/bin/samtools-1.2/samtools view -S -b -h - | /home/yara/bin/samtools-1.2/samtools sort - SRR7748055-bwamem 
 /home/yara/bin/samtools-1.2/samtools index SRR7748055-bwamem.bam 


SRR7748055-bwamem.bam is created just fine (along with all of the other expected output files) and nasp_bwamem_SRR7748055.out is no longer empty and has the following output:

/bin/sh: 1: [: -lt: unexpected operator
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 264932 sequences (40000195 bp)...
[M::process] read 264940 sequences (40000046 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (48, 124175, 19, 45)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (251, 2030, 6720)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19658)
[M::mem_pestat] mean and std.dev: (3674.85, 3528.39)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 26127)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (337, 434, 523)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 895)
[M::mem_pestat] mean and std.dev: (427.68, 112.44)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1081)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (629, 1561, 3677)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 9773)
[M::mem_pestat] mean and std.dev: (2039.11, 1699.18)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 12821)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (263, 659, 6786)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19832)
[M::mem_pestat] mean and std.dev: (3588.33, 3453.89)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 26355)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 264932 reads in 16.160 CPU sec, 5.665 real sec
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (60, 123617, 6, 53)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (233, 1026, 6610)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19364)
[M::mem_pestat] mean and std.dev: (3218.17, 3305.13)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25741)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (333, 429, 520)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 894)
[M::mem_pestat] mean and std.dev: (424.50, 112.90)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1081)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (352, 6570, 6715)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19441)
[M::mem_pestat] mean and std.dev: (3943.72, 3208.43)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25804)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 264940 reads in 17.388 CPU sec, 6.902 real sec
[M::process] read 264926 sequences (40000301 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (75, 124089, 5, 48)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (218, 359, 6554)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19226)
[M::mem_pestat] mean and std.dev: (2625.77, 3300.12)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25562)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (337, 433, 522)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 892)
[M::mem_pestat] mean and std.dev: (427.38, 112.52)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1077)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (241, 3556, 6602)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19324)
[M::mem_pestat] mean and std.dev: (3751.46, 3423.10)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25685)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 264926 reads in 15.656 CPU sec, 5.231 real sec
[M::process] read 264932 sequences (40000066 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (58, 123721, 11, 52)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (232, 499, 6688)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19600)
[M::mem_pestat] mean and std.dev: (3280.31, 3392.62)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 26056)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (333, 429, 520)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 894)
[M::mem_pestat] mean and std.dev: (424.48, 112.94)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1081)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (2591, 2781, 3690)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (393, 5888)
[M::mem_pestat] mean and std.dev: (2788.00, 1458.82)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 6987)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (307, 6474, 6735)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19591)
[M::mem_pestat] mean and std.dev: (4206.85, 3202.62)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 26019)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 264932 reads in 17.248 CPU sec, 5.735 real sec
[M::process] read 264926 sequences (40000045 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (65, 124747, 15, 41)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (221, 397, 6551)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19211)
[M::mem_pestat] mean and std.dev: (2672.51, 3182.44)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25541)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (338, 435, 523)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 893)
[M::mem_pestat] mean and std.dev: (428.53, 112.15)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1078)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (530, 837, 1874)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 4562)
[M::mem_pestat] mean and std.dev: (876.08, 601.68)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 5906)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (449, 6476, 6692)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19178)
[M::mem_pestat] mean and std.dev: (4631.76, 3042.13)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25421)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 264926 reads in 15.360 CPU sec, 5.183 real sec
[M::process] read 264932 sequences (40000048 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (51, 124298, 11, 60)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (296, 504, 6649)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19355)
[M::mem_pestat] mean and std.dev: (3041.92, 3193.04)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25708)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (335, 431, 521)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 893)
[M::mem_pestat] mean and std.dev: (426.00, 112.51)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1079)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (1141, 2855, 4557)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 11389)
[M::mem_pestat] mean and std.dev: (2770.82, 1670.37)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 14805)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (351, 6231, 6681)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19341)
[M::mem_pestat] mean and std.dev: (3861.83, 3305.11)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25671)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 264932 reads in 16.596 CPU sec, 5.505 real sec
[M::process] read 264932 sequences (40000144 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (65, 124719, 9, 45)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (269, 3622, 6766)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19760)
[M::mem_pestat] mean and std.dev: (3737.54, 3398.26)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 26257)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (338, 434, 523)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 893)
[M::mem_pestat] mean and std.dev: (428.02, 112.17)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1078)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (287, 6152, 6586)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19184)
[M::mem_pestat] mean and std.dev: (3816.11, 3420.67)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25483)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 264932 reads in 15.268 CPU sec, 5.090 real sec
[M::process] read 204798 sequences (30921266 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (43, 96151, 3, 31)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (224, 661, 6638)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19466)
[M::mem_pestat] mean and std.dev: (3476.65, 3414.23)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25880)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (335, 430, 521)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 893)
[M::mem_pestat] mean and std.dev: (425.66, 112.37)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1079)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (447, 6362, 6711)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19239)
[M::mem_pestat] mean and std.dev: (3953.84, 3160.29)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25503)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 204798 reads in 12.112 CPU sec, 4.070 real sec
[main] Version: 0.7.12-r1039
[main] CMD: /usr/bin/bwa mem -R @RG\tID:SRR7748055\tSM:SRR7748055 -t 4 /home/yara/Documents/staph_clinical_isolates/data/SNPs_analysis/alignments/nasp_results/reference/reference.fasta /home/yara/Documents/staph_clinical_isolates/data/SNPs_analysis/alignments/nasp_results/trimmed/SRR7748055_R1_trimmed.fastq /home/yara/Documents/staph_clinical_isolates/data/SNPs_analysis/alignments/nasp_results/trimmed/SRR7748055_R2_trimmed.fastq
[main] Real time: 64.284 sec; CPU: 127.568 sec
[bam_sort_core] merging from 2 files...

I tried to execute all of the commands in the runlog.txt leading up to bwamem and they all run just fine.

Any ideas?

**Comment by yseif** [comment]
I think that the program is likely stopping after running this command:

04/12/2019 15:01:39 INFO     command = java -jar /usr/share/java/trimmomatic-0.35.jar PE -threads 4 /chosen_path/SRR7748055/SRR7748055_1.fastq /hchosen_path/SRR7748055/SRR7748055_2.fastq SRR7748055_R1_trimmed.fastq SRR7748055_R1_unpaired.fastq SRR7748055_R2_trimmed.fastq SRR7748055_R2_unpaired.fastq ILLUMINACLIP:/usr/local/lib/python3.5/dist-packages/nasp/illumina_adapters_all.fasta:4:30:10:1:true  MINLEN:80
04/12/2019 15:01:39 DEBUG    submit_command = while [ `free -m | grep cache: | awk '{ print $4 }'` -lt 14250 ]; do sleep 300; done; java -jar /usr/share/java/trimmomatic-0.35.jar PE -threads 4 /chosen_path/SRR7748055/SRR7748055_1.fastq /chosen_path/SRR7748055_2.fastq SRR7748055_R1_trimmed.fastq SRR7748055_R1_unpaired.fastq SRR7748055_R2_trimmed.fastq SRR7748055_R2_unpaired.fastq ILLUMINACLIP:/usr/local/lib/python3.5/dist-packages/nasp/illumina_adapters_all.fasta:4:30:10:1:true  MINLEN:80
04/12/2019 15:01:39 INFO     jobid = 12225

with the following error showing up on the nasp+trim_SRR7748055.out file:
/bin/sh: 1: [: -lt: unexpected operator

The output in the trimmed folder indicates that trimmomatic was run just fine. So is the problem here: "while [ `free -m | grep cache: | awk '{ print $4 }'` -lt 14250 ];"
