### ISSUE TITLE
break off and prompt "total_mem = 62"

### ISSUE THREAD

**Issue by zhaoxvwahaha** [TGenNorth/NASP#13]
I use the linux system: CentOS release 6.9

$nasp
Welcome to NASP version 1.0.0.

Where would you like output files to be written [nasp_results]? result

Output folder /hwfssz1/ST_META/F12ZHQYJSY1009_MerckCDiff_ZHL/04.C.Diff/36.NASP/result already exists!
Files in it may be overwritten!
Should we continue anyway [N]? y

Where is the reference fasta file you would like to use? Clostridium_difficile_CD196.fasta

Do you want to check the reference for duplicated regions
and skip SNPs that fall in those regions [Y]? y

What system do you use for job management (PBS/TORQUE, SLURM, SGE/OGE, and 'none' are currently supported) [PBS]? none

Do you have fasta files for external genomes you wish to include [Y]? y
Where are these files located [/hwfssz1/ST_META/F12ZHQYJSY1009_MerckCDiff_ZHL/04.C.Diff/36.NASP]? assembly/

Do you have read files you wish to include [Y]? y
Where are these files located [/hwfssz1/ST_META/F12ZHQYJSY1009_MerckCDiff_ZHL/04.C.Diff/36.NASP]? reads/

Do you have pre-aligned SAM/BAM files you wish to include [N]? n

Do you have pre-called VCFfiles you wish to include [N]? n
Would you like to set advanced MatrixGenerator settings [N]? n

Do you want to create a master_masked matrix that includes all positions with low-quality positions that failed the coverage or proportion filter masked with an 'N' [N]? n
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62

I've no idea what happened, could you give me some help, thanks in advance.

**Comment by DarwinW13** [comment]
NASP is really meant to be run using a job manager like Torque or SLURM. Running without one is more for testing purposes, but it should work fine for smaller datasets. After the UI finishes asking all the questions it needs to set up the jobs, then it starts scheduling the jobs, and after they are all submitted the main script exits. You should see a bunch of jobs if you use something like 'ps' or 'top'. They will be in a sleep state and waking up every few minutes to check if there are enough resources available to start running, which hopefully happens at some point. If all goes well, eventually all the jobs will be run and your SNP matrix will be created. If anything fails there should be output files in the various sub-directories of your output directory. For instance if you choose to run BWA, then the output of boa will all be written to a 'bwa' directory. However, from your output it looks like you specified a read directory, but the program didn't ask you about aligners -- this means it didn't recognize any read files in your read directory. It uses a complex regular expression to identify and pair your reads, so if you can give me some sample read file names I can try to determine why it didn't recognize any of them.

**Comment by zhaoxvwahaha** [comment]
Thank you for your patient reply,
I only put a pair of files in the directory to test, the reads file names are:
1-0001_Clean.pair.1.fq.gz  1-0001_Clean.pair.2.fq.gz

**Comment by zhaoxvwahaha** [comment]
$ls reads
1-0001_Clean.pair_1.fq.gz  1-0001_Clean.pair_2.fq.gz
I've changed the reads file name ,but the error is also same.


Do you have read files you wish to include [Y]? y
Where are these files located [/hwfssz1/ST_META/F12ZHQYJSY1009_MerckCDiff_ZHL/04.C.Diff/36.NASP]? reads

Do you have pre-aligned SAM/BAM files you wish to include [N]? n

Do you have pre-called VCFfiles you wish to include [N]? n
Would you like to set advanced MatrixGenerator settings [N]? n

Do you want to create a master_masked matrix that includes all positions with low-quality positions that failed the coverage or proportion filter masked with an 'N' [N]? n
total_mem = 62
total_mem = 62
total_mem = 62
total_mem = 62
