### ISSUE TITLE
Folder set up, but no processing

### ISSUE THREAD

**Issue by r0sies** [TGenNorth/NASP#14]
Hi,

I can't seem to get NASP to process.
It can set up all the folders
ls
bwamem  matrices  matrix_dto.xml  nasp_matrix.out  reference  results-config.xml  runlog.txt  samtools  statistics  trimmed

but no processing is done.

I have not specified a job scheduler for testing purposes - also out ICT advised this to be more appropriate so that it would run using the resources described in our PBS script.
We have PBSPro on our HPC. When I run it using PBS and using a HEREDOC to answer the questions, I receive the error "unknown flag -d"

Thanks,
Rosie

---
Welcome to NASP version 1.0.0.

Where would you like output files to be written [nasp_results]?
Where is the reference fasta file you would like to use?
Do you want to check the reference for duplicated regions
and skip SNPs that fall in those regions [Y]?
What system do you use for job management (PBS/TORQUE, SLURM, SGE/OGE, and 'none' are currently supported) [PBS]?
Do you have fasta files for external genomes you wish to include [Y]?
Do you have read files you wish to include [Y]? Where are these files located [/project/RDS-SMS-IPD_genomics-RW/Rebecca3/NASP/test]?
Would you like to use Trimmomatic to trim your reads first [N]?   What adapter file are you using for trimming [/usr/local/python/3.5.1/l
ib/python3.5/site-packages/nasp/illumina_adapters_all.fasta]?   Would you also like to perform quality trimming [N]?   What quality trimm
ing parameters do you want to use [SLIDINGWINDOW:5:20]?   What is the minimum length read to keep after trimming [80]? Would you like to
set advanced ReadTrimmer settings [N]?
This pipeline currently supports four aligners: BWA, Bowtie2, Novoalign, and SNAP.
You can also provide pre-aligned BAM files, and you can choose as many options as you want.

Would you like to run BWA mem [Y]? Would you like to set advanced BWA-mem settings [N]?
Would you like to run Bowtie2 [Y]?
Would you like to run Novoalign [N]?
Would you like to run SNAP [N]?
Do you have pre-aligned SAM/BAM files you wish to include [N]?
This pipeline currently supports four SNP callers: GATK, SolSNP, VarScan, and SAMtools, and you can provide VCF files.
You can choose as many options as you want.

Would you like to run GATK [Y]?
Would you like to run SolSNP [N]?
Would you like to run VarScan [Y]?
Would you like to run SAMtools [Y]? Would you like to set advanced SAMtools settings [N]?
Do you have pre-called VCFfiles you wish to include [N]?
This pipeline can do filtering based on coverage.
If you do not want filtering based on coverage, enter 0.
What is your minimum coverage threshold [10]?
This pipeline can do filtering based on the proportion of reads that match the call made by the SNP caller.
If you do not want filtering based on proportion, enter 0.
What is the minimum acceptable proportion [0.9]? Would you like to set advanced MatrixGenerator settings [N]?
Do you want to create a master_masked matrix that includes all positions with low-quality positions that failed the coverage or proportion filter masked with an 'N' [N]? total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125
total_mem = 125

**Comment by yseif** [comment]
I'm having the same issue. Did you manage to solve it?
