### ISSUE TITLE
qsub - command not found

### ISSUE THREAD

**Issue by siahahmed** [TGenNorth/NASP#16]
I got this issue when running nasp downloaded with conda on mac book pro v10.12.6
Job not submitted: /bin/sh: qsub: command not found
Thanks

**Comment by corburn** [comment]
@siahahmed there are two issues. The first issue is NASP was designed to run on a system with a job manager. The following prompt is where you can select a job scheduler: 

```
What system do you use for job management (PBS/TORQUE, SLURM, SGE/OGE, and 'none' are currently supported) [PBS]?
```

The second issue is OSX is not supported. The nasp 1.0.2a1 package was created by a member of the bioconda community and should probably be removed from the channel.
