### ISSUE TITLE
Run fails when VCF and BAM files provided

### ISSUE THREAD

**Issue by sariya** [TGenNorth/NASP#4]
NASP `version: 1.0.0.`
Running nasp:
`nasp.py`
Job scheduler: SLURM

Upon asked do you have bam files, **and** VCF files - I provide path for both, as I've both files generated from my previous output files. I get the error attached in the word file.

It works fine when I provide VCF file **only**. 
[Traceback.docx](https://github.com/TGenNorth/NASP/files/114526/Traceback.docx)

**Comment by corburn** [comment]
```
OSError: [Errno 7] Argument list too long
```

Thank you for reporting this issue. The command submitted to the job scheduler exceeded the max line length. We will have to adjust the way bams are submitted to avoid this limit.
