### ISSUE TITLE
error after installation 

### ISSUE THREAD

**Issue by dpchris** [TGenNorth/NASP#9]
Hello, 

i'm trying to use NASP.
I have installed it from github with : _git clone --recursive https://github.com/TGenNorth/NASP.git_

I have then run _python setup.py build_ and _python setup.py install_  
I had no errors during this steps.

But when I run nasp, I got the following error  : 
_$ nasp
Traceback (most recent call last):
  File "/usr/local/bin/nasp", line 9, in <module>
    load_entry_point('nasp==1.0.2', 'console_scripts', 'nasp')()
  File "/usr/local/lib/python2.7/dist-packages/nasp-1.0.2-py2.7.egg/nasp/nasp.py", line 571, in main
    import nasp.dispatcher as dispatcher
ImportError: No module named dispatcher_

I don't know how to solve this issue and I didn't find how to do it.

Can anybody help me ? 
Thanks in advance.

Best regards.

**Comment by corburn** [comment]
Hello @dpchris,

You are using Python 2. The NASP dispatcher is using Python 3.

If both Python 2 and 3 installed, you can typically use python3/pip3/etc to specify python 3 commands.

NASP is published on [pypi](https://pypi.python.org/pypi) so you could install it by running `pip3 install nasp`.

**Comment by dpchris** [comment]
Thanks a lot, i will try pip3.

I have indeed python 2 and 3, i tried with python 3 but was unaware of pip3.

regards.

________________________________
De : Jason Travis [notifications@github.com]
Envoyé : vendredi 27 janvier 2017 16:20
À : TGenNorth/NASP
Cc : CHRISTIANY David; Mention
Objet : Re: [TGenNorth/NASP] error after installation (#9)


Hello @dpchris<https://github.com/dpchris>,

You are using Python 2. The NASP dispatcher is using Python 3.

If both Python 2 and 3 installed, you can typically use python3/pip3/etc to specify python 3 commands.

NASP is published on pypi<https://pypi.python.org/pypi> so you could install it by running pip3 install nasp.
